plugins {
    id 'java-library'
}

group = 'com.example'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}

jar {
    archiveBaseName = 'gradle-lib'
    archiveVersion = '0.1.0'
}

tasks.named('test') {
    useJUnit()
}
