[package]
name = "curie-protobuf"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Curie plugin: generate Java + gRPC stubs from .proto files"

[[bin]]
name = "curie-protobuf"
path = "src/main.rs"

[dependencies]
anyhow       = "1"
curie-plugin = { version = "0.6.0", path = "../../curie-plugin" }
serde        = { version = "1", features = ["derive"] }
serde_json   = "1"
walkdir      = "2"
