//! `Curie.lock` — pins exact unique versions for SNAPSHOT dependencies.
//!
//! When any dependency resolves as a unique Maven snapshot
//! (`1.0-20260610.123456-3`), Curie writes (or updates) `Curie.lock` in the
//! project root so subsequent builds reproduce the same classpath without
//! re-querying snapshot metadata.  `curie build -U` / `--update-snapshots`,
//! or deleting this file, re-fetches SNAPSHOT metadata from the repository
//! (there is no Maven-style same-day freshness window).
//!
//! Format (TOML):
//!
//! ```toml
//! # Auto-generated by Curie. Do not edit by hand unless you know why.
//!
//! [snapshots]
//! "com.example:foo:1.0-SNAPSHOT" = "1.0-20260610.123456-3"
//! ```

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, HashMap};
use std::path::Path;

/// On-disk name of the lockfile (project root).
pub const LOCKFILE_NAME: &str = "Curie.lock";

#[derive(Debug, Default, Serialize, Deserialize, PartialEq, Eq)]
struct LockFile {
    /// `group:artifact:baseVersion` → unique timestamped version.
    #[serde(default)]
    snapshots: BTreeMap<String, String>,
}

/// Load snapshot pins from `project_root/Curie.lock`.
///
/// Returns an empty map when the file is absent.  A present but unparseable
/// file is a hard error (fail the build, do not silently ignore).
pub fn load_snapshot_pins(project_root: &Path) -> Result<HashMap<String, String>> {
    let path = project_root.join(LOCKFILE_NAME);
    if !path.exists() {
        return Ok(HashMap::new());
    }
    let text = std::fs::read_to_string(&path)
        .with_context(|| format!("failed to read {}", path.display()))?;
    let lock: LockFile = toml::from_str(&text)
        .with_context(|| format!("failed to parse {}", path.display()))?;
    Ok(lock.snapshots.into_iter().collect())
}

/// Write `Curie.lock` with the given snapshot pins, or remove it when empty.
///
/// Called after a successful resolve that may have SNAPSHOT dependencies.
/// When `pins` is empty the lockfile is deleted (so removing the last
/// snapshot dep cleans up automatically).
pub fn write_snapshot_pins(project_root: &Path, pins: &BTreeMap<String, String>) -> Result<()> {
    let path = project_root.join(LOCKFILE_NAME);
    if pins.is_empty() {
        if path.exists() {
            std::fs::remove_file(&path)
                .with_context(|| format!("failed to remove {}", path.display()))?;
        }
        return Ok(());
    }

    let lock = LockFile {
        snapshots: pins.clone(),
    };
    let body = toml::to_string_pretty(&lock)
        .context("failed to serialise Curie.lock")?;
    let header = "\
# Auto-generated by Curie. Pins unique versions of SNAPSHOT dependencies.
# Run `curie build -U` (or `--update-snapshots`), or delete this file, to
# re-fetch SNAPSHOT metadata from the repository and refresh the pins.

";
    std::fs::write(&path, format!("{header}{body}"))
        .with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

/// Resolve dependencies with lockfile integration: load pins, resolve,
/// merge any new SNAPSHOT pins into `Curie.lock`.
///
/// Pins from other scopes (e.g. production vs test) are preserved: each
/// resolve only upserts the snapshots it actually resolved.  Stale pins for
/// removed dependencies are harmless (unused) and can be cleared by deleting
/// `Curie.lock`.
pub fn resolve_with_lock(
    project_root: &Path,
    deps: &[curie_deps::DepEntry],
    mut opts: curie_deps::ResolveOptions,
    update_snapshots: bool,
) -> Result<Vec<std::path::PathBuf>> {
    opts.snapshot_pins = load_snapshot_pins(project_root)?;
    opts.update_snapshots = update_snapshots;

    let result = curie_deps::resolve_full(deps, &opts, &[])
        .context("dependency resolution failed")?;

    if !result.snapshot_pins.is_empty() {
        let mut merged: BTreeMap<String, String> = load_snapshot_pins(project_root)?
            .into_iter()
            .collect();
        for (k, v) in result.snapshot_pins {
            merged.insert(k, v);
        }
        write_snapshot_pins(project_root, &merged)?;
    }

    Ok(result.jars)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    #[test]
    fn load_missing_lock_returns_empty() {
        let dir = tempfile::tempdir().unwrap();
        let pins = load_snapshot_pins(dir.path()).unwrap();
        assert!(pins.is_empty());
    }

    #[test]
    fn write_and_load_roundtrip() {
        let dir = tempfile::tempdir().unwrap();
        let mut pins = BTreeMap::new();
        pins.insert(
            "com.example:foo:1.0-SNAPSHOT".into(),
            "1.0-20260115.120000-1".into(),
        );
        write_snapshot_pins(dir.path(), &pins).unwrap();

        let path = dir.path().join(LOCKFILE_NAME);
        assert!(path.exists());
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("Auto-generated by Curie"));
        assert!(text.contains("com.example:foo:1.0-SNAPSHOT"));

        let loaded = load_snapshot_pins(dir.path()).unwrap();
        assert_eq!(
            loaded.get("com.example:foo:1.0-SNAPSHOT").map(String::as_str),
            Some("1.0-20260115.120000-1")
        );
    }

    #[test]
    fn write_empty_removes_lockfile() {
        let dir = tempfile::tempdir().unwrap();
        let mut pins = BTreeMap::new();
        pins.insert("g:a:1.0-SNAPSHOT".into(), "1.0-1".into());
        write_snapshot_pins(dir.path(), &pins).unwrap();
        assert!(dir.path().join(LOCKFILE_NAME).exists());

        write_snapshot_pins(dir.path(), &BTreeMap::new()).unwrap();
        assert!(!dir.path().join(LOCKFILE_NAME).exists());
    }

    #[test]
    fn malformed_lock_is_hard_error() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join(LOCKFILE_NAME), "not = [valid").unwrap();
        assert!(load_snapshot_pins(dir.path()).is_err());
    }
}
