//! Maven `pom.xml` generation for `curie maven sync` (see
//! `_design/MAVEN-SYNC.md`).
//!
//! Maps a Curie [`Descriptor`] plus the on-disk source layout to a `pom.xml`
//! such that `mvn verify` produces the same build outputs as `curie build`.
//! The module is split into three layers:
//!
//! - [`discover_layout`] inspects the project directory for source/test/
//!   resource roots, mirroring the layouts `compile.rs`/`test.rs` support.
//! - [`build_project`] + [`render`] turn a descriptor (+ layout) into a
//!   [`MavenProject`] model and then into deterministic XML.
//! - [`sync_pom`] wraps both with fingerprint-based incremental writes and
//!   the "don't clobber a hand-written pom.xml" safety check.

use crate::compile::{flat_package_src_dirs, flat_package_test_dirs};
use crate::descriptor::{Descriptor, DependencyValue};
use crate::incremental::walk_files;
use anyhow::{Context, Result};
use quick_xml::events::{BytesDecl, BytesEnd, BytesStart, BytesText, Event};
use quick_xml::Writer;
use sha2::{Digest, Sha256};
use std::collections::BTreeSet;
use std::io::Cursor;
use std::path::{Path, PathBuf};

/// `groupId` fallback for projects that don't declare one in `Curie.toml`.
pub const GENERATED_GROUP_ID: &str = "curie.generated";

/// Maven's reproducible-builds property; matches `jar.rs::epoch()`.
pub const OUTPUT_TIMESTAMP: &str = "2024-01-01T00:00:00Z";

/// Bump to force every generated `pom.xml` to be regenerated even when
/// none of the other fingerprint inputs changed.
pub const SCHEMA_VERSION: u32 = 1;

/// Human-readable line written into every generated POM, immediately above
/// the `curie-maven-fingerprint:` line.
const GENERATED_MARKER: &str = "Generated by curie maven sync from Curie.toml — DO NOT EDIT.";
const FINGERPRINT_PREFIX: &str = "curie-maven-fingerprint: ";

/// Default `<groupId>` for plugins declared without one (the standard Maven
/// plugin prefix).
const DEFAULT_PLUGIN_GROUP_ID: &str = "org.apache.maven.plugins";

/// Pinned versions of every Maven plugin the generator emits.  Versions are
/// part of the reproducibility surface: bump deliberately, alongside
/// [`SCHEMA_VERSION`].  Checked against Maven Central on 2026-06-11.
pub mod plugin_versions {
    pub const COMPILER: &str = "3.15.0";
    pub const SUREFIRE: &str = "3.5.6";
    pub const JAR: &str = "3.5.0";
    pub const SHADE: &str = "3.6.2";
    pub const DEPENDENCY: &str = "3.11.0";
    pub const BUILD_HELPER: &str = "3.6.0";
    pub const GMAVENPLUS: &str = "4.2.0";
    pub const JACOCO: &str = "0.8.13";
}

const BUILD_HELPER_GROUP_ID: &str = "org.codehaus.mojo";
const BUILD_HELPER_ARTIFACT_ID: &str = "build-helper-maven-plugin";

// ---------------------------------------------------------------------------
// Layout discovery
// ---------------------------------------------------------------------------

/// Source/test/resource roots discovered on disk, all relative to the
/// project root.  Mirrors the layouts `compile.rs`/`test.rs` support
/// (Maven-style `src/main/{java,kotlin,groovy}`, flat-package dot-named
/// dirs under `src/`/`tests/`, and bare `src/`).
#[derive(Debug, Default, Clone, PartialEq, Eq)]
pub struct MavenLayout {
    /// Production source roots, sorted.  The first becomes
    /// `<sourceDirectory>` (or is omitted when it is Maven's default,
    /// `src/main/java`); the rest become `build-helper-maven-plugin:add-source`
    /// entries.
    pub src_roots: Vec<PathBuf>,
    /// Test source roots, sorted.  Same `<testSourceDirectory>` /
    /// `add-test-source` split as [`Self::src_roots`].
    pub test_roots: Vec<PathBuf>,
    pub resources: Option<PathBuf>,
    pub test_resources: Option<PathBuf>,
    /// Ant-style filename patterns (e.g. `**/*Test.java`) to exclude from
    /// the main compile because Curie treats co-located `*Test`/`*Tests`/
    /// `*Spec` files in production roots as test sources.  Sorted.
    pub colocated_test_excludes: Vec<String>,
}

/// Discover the Maven-equivalent source layout for `project_root`.
pub fn discover_layout(project_root: &Path) -> MavenLayout {
    let mut src_roots = production_source_roots(project_root);
    let mut test_roots = test_source_roots(project_root);

    let colocated_test_excludes = colocated_test_exclude_patterns(project_root, &src_roots);
    if !colocated_test_excludes.is_empty() {
        for root in &src_roots {
            if !test_roots.contains(root) {
                test_roots.push(root.clone());
            }
        }
    }

    src_roots.sort();
    test_roots.sort();

    MavenLayout {
        src_roots,
        test_roots,
        resources: first_existing_dir(project_root, &["src/main/resources", "resources"]),
        test_resources: first_existing_dir(project_root, &["src/test/resources", "test-resources"]),
        colocated_test_excludes,
    }
}

/// Production source roots: Maven-style `src/main/{java,kotlin,groovy}`,
/// flat-package dot-named dirs under `src/`, and bare `src/` when it
/// directly contains source files (layouts A-E in `compile.rs`).
fn production_source_roots(project_root: &Path) -> Vec<PathBuf> {
    let mut roots = Vec::new();
    for candidate in ["src/main/java", "src/main/kotlin", "src/main/groovy"] {
        if project_root.join(candidate).exists() {
            roots.push(PathBuf::from(candidate));
        }
    }
    roots.extend(relative_to(project_root, flat_package_src_dirs(project_root)));

    let bare_src = project_root.join("src");
    if bare_src.exists() && !roots.iter().any(|r| r == Path::new("src")) && has_direct_sources(&bare_src) {
        roots.push(PathBuf::from("src"));
    }
    roots
}

/// Test source roots: Maven-style `src/test/{java,kotlin,groovy}` and
/// flat-package dot-named dirs under `tests/`.
fn test_source_roots(project_root: &Path) -> Vec<PathBuf> {
    let mut roots = Vec::new();
    for candidate in ["src/test/java", "src/test/kotlin", "src/test/groovy"] {
        if project_root.join(candidate).exists() {
            roots.push(PathBuf::from(candidate));
        }
    }
    roots.extend(relative_to(project_root, flat_package_test_dirs(project_root)));
    roots
}

/// Re-root absolute paths under `project_root` (as returned by
/// `flat_package_*_dirs`) to paths relative to it.
fn relative_to(project_root: &Path, paths: Vec<PathBuf>) -> Vec<PathBuf> {
    paths
        .into_iter()
        .filter_map(|p| p.strip_prefix(project_root).ok().map(Path::to_path_buf))
        .collect()
}

/// `true` if `dir` directly contains a `.java`, `.kt`, or `.groovy` file
/// (layout E: bare `src/` with unnamed-class sources).
fn has_direct_sources(dir: &Path) -> bool {
    std::fs::read_dir(dir)
        .ok()
        .map(|entries| {
            entries.filter_map(|e| e.ok()).any(|e| {
                e.file_type().map(|t| t.is_file()).unwrap_or(false)
                    && matches!(
                        e.path().extension().and_then(|s| s.to_str()),
                        Some("java") | Some("kt") | Some("groovy")
                    )
            })
        })
        .unwrap_or(false)
}

/// First of `candidates` (relative to `project_root`) that exists, as a
/// path relative to `project_root`.
fn first_existing_dir(project_root: &Path, candidates: &[&str]) -> Option<PathBuf> {
    candidates
        .iter()
        .map(PathBuf::from)
        .find(|rel| project_root.join(rel).exists())
}

/// Filename patterns for co-located `*Test`/`*Tests`/`*Spec` sources found
/// directly under any of `src_roots` — these are compiled by Curie as test
/// sources (`test.rs::discover_test_sources`), not production sources.
fn colocated_test_exclude_patterns(project_root: &Path, src_roots: &[PathBuf]) -> Vec<String> {
    let mut extensions: BTreeSet<&str> = BTreeSet::new();
    for root in src_roots {
        for entry in walk_files(&project_root.join(root)) {
            let name = entry.file_name().to_string_lossy().into_owned();
            for ext in ["java", "kt", "groovy"] {
                if name.ends_with(&format!("Test.{ext}"))
                    || name.ends_with(&format!("Tests.{ext}"))
                    || name.ends_with(&format!("Spec.{ext}"))
                {
                    extensions.insert(ext);
                }
            }
        }
    }

    let mut patterns = Vec::new();
    for ext in extensions {
        patterns.push(format!("**/*Test.{ext}"));
        patterns.push(format!("**/*Tests.{ext}"));
        patterns.push(format!("**/*Spec.{ext}"));
    }
    patterns
}

// ---------------------------------------------------------------------------
// POM model
// ---------------------------------------------------------------------------

/// A `<dependency>` entry.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MavenDependency {
    pub group_id: String,
    pub artifact_id: String,
    /// `None` when the version is supplied by an imported BOM (Curie's
    /// `version = ""`) — the `<version>` element is omitted.
    pub version: Option<String>,
    pub scope: Option<String>,
    /// `(groupId, artifactId)` pairs from `exclusions = ["g:a", ...]`.
    pub exclusions: Vec<(String, String)>,
}

/// One entry of the `pinTransitive` resolved dependency closure
/// (`group:artifact -> version`), materialized into
/// `<dependencyManagement>` when `[maven] pinTransitive = true`.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct PinnedDependency {
    pub group_id: String,
    pub artifact_id: String,
    pub version: String,
}

/// A `<dependencyManagement><dependencies>` entry: either an imported BOM
/// (`<type>pom</type><scope>import</scope>`) or an explicit managed version
/// (from `pinTransitive`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MavenManagedDependency {
    pub group_id: String,
    pub artifact_id: String,
    pub version: String,
    pub is_import: bool,
}

/// A generic XML element used to render plugin `<configuration>` blocks
/// without a dedicated Rust type per plugin.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum XmlNode {
    /// `<name>text</name>` — text is escaped on render.
    Text(String, String),
    /// `<name>child1 child2 ...</name>`
    Element(String, Vec<XmlNode>),
}

impl XmlNode {
    pub fn text(name: impl Into<String>, value: impl Into<String>) -> Self {
        XmlNode::Text(name.into(), value.into())
    }

    pub fn element(name: impl Into<String>, children: Vec<XmlNode>) -> Self {
        XmlNode::Element(name.into(), children)
    }
}

/// A `<plugin>` entry under `<build><plugins>`.
#[derive(Debug, Clone, Default)]
pub struct MavenPlugin {
    /// `None` renders as [`DEFAULT_PLUGIN_GROUP_ID`].
    pub group_id: Option<String>,
    pub artifact_id: String,
    pub version: String,
    pub configuration: Vec<XmlNode>,
    pub executions: Vec<MavenExecution>,
}

/// An `<execution>` entry under a plugin's `<executions>`.
#[derive(Debug, Clone, Default)]
pub struct MavenExecution {
    pub id: Option<String>,
    pub phase: Option<String>,
    pub goals: Vec<String>,
    pub configuration: Vec<XmlNode>,
}

/// The full model rendered into a `pom.xml`.
#[derive(Debug, Clone, Default)]
pub struct MavenProject {
    pub group_id: String,
    pub artifact_id: String,
    pub version: String,
    pub packaging: String,
    pub properties: Vec<(String, String)>,
    pub layout: MavenLayout,
    pub dependencies: Vec<MavenDependency>,
    pub managed_dependencies: Vec<MavenManagedDependency>,
    pub plugins: Vec<MavenPlugin>,
}

// ---------------------------------------------------------------------------
// Descriptor -> MavenProject
// ---------------------------------------------------------------------------

/// Build the [`MavenProject`] model for an `[application]`/`[library]`
/// descriptor.  `pinned` is the resolved transitive closure to materialize
/// into `<dependencyManagement>` when `[maven] pinTransitive = true`
/// (pass `&[]` when disabled).
pub fn build_project(desc: &Descriptor, project_root: &Path, pinned: &[PinnedDependency]) -> Result<MavenProject> {
    if desc.is_workspace() {
        anyhow::bail!("build_project: workspace descriptors are handled by the aggregator generator");
    }
    if desc.is_bom() {
        anyhow::bail!("build_project: BOM descriptors are handled by the BOM POM generator");
    }

    let layout = discover_layout(project_root);
    let plugins = build_helper_plugins(&layout);

    Ok(MavenProject {
        group_id: desc.group_id().unwrap_or(GENERATED_GROUP_ID).to_string(),
        artifact_id: desc.buildable_name().to_string(),
        version: desc.buildable_version().to_string(),
        packaging: "jar".to_string(),
        properties: default_properties(desc),
        dependencies: build_dependencies(desc)?,
        managed_dependencies: build_managed_dependencies(desc, pinned)?,
        layout,
        plugins,
    })
}

fn default_properties(desc: &Descriptor) -> Vec<(String, String)> {
    vec![
        ("maven.compiler.release".to_string(), desc.java.effective().to_string()),
        ("project.build.sourceEncoding".to_string(), "UTF-8".to_string()),
        ("project.build.outputTimestamp".to_string(), OUTPUT_TIMESTAMP.to_string()),
    ]
}

fn build_dependencies(desc: &Descriptor) -> Result<Vec<MavenDependency>> {
    let mut deps = Vec::new();
    for (coord, dep) in &desc.dependencies {
        deps.push(maven_dependency(coord, dep, "compile")?);
    }
    for (coord, dep) in &desc.test_dependencies {
        deps.push(maven_dependency(coord, dep, "test")?);
    }
    Ok(deps)
}

fn maven_dependency(coord: &str, dep: &DependencyValue, scope: &str) -> Result<MavenDependency> {
    let (group_id, artifact_id) = split_coord(coord)?;
    let version = dep.version();
    let exclusions = dep
        .exclusions()
        .iter()
        .map(|e| split_coord(e))
        .collect::<Result<Vec<_>>>()?;
    Ok(MavenDependency {
        group_id,
        artifact_id,
        version: if version.is_empty() { None } else { Some(version.to_string()) },
        scope: Some(scope.to_string()),
        exclusions,
    })
}

/// Build `<dependencyManagement>` entries.
///
/// Order:
/// 1. `pinTransitive` pins (sorted by `group:artifact`), when non-empty.
///    Maven's dependencyManagement merge expands BOM imports in place and
///    keeps the *first* declaration for a given `group:artifact`, so pins
///    must come first to "dominate" any BOM-supplied version as the design
///    intends.
/// 2. The member's own `[bom-imports]` + `[test-bom-imports]` (highest
///    precedence among imports — Maven's first-wins import semantics).
/// 3. Workspace-inherited BOM imports (lower precedence).
fn build_managed_dependencies(desc: &Descriptor, pinned: &[PinnedDependency]) -> Result<Vec<MavenManagedDependency>> {
    let mut managed = Vec::new();

    let mut sorted_pins = pinned.to_vec();
    sorted_pins.sort();
    for pin in sorted_pins {
        managed.push(MavenManagedDependency {
            group_id: pin.group_id,
            artifact_id: pin.artifact_id,
            version: pin.version,
            is_import: false,
        });
    }

    for (coord, version) in desc.bom_imports.iter().chain(desc.test_bom_imports.iter()) {
        let (group_id, artifact_id) = split_coord(coord)?;
        managed.push(MavenManagedDependency { group_id, artifact_id, version: version.clone(), is_import: true });
    }
    for (coord, version) in desc.inherited_bom_imports.iter().chain(desc.inherited_test_bom_imports.iter()) {
        let (group_id, artifact_id) = split_coord(coord)?;
        managed.push(MavenManagedDependency { group_id, artifact_id, version: version.clone(), is_import: true });
    }

    Ok(managed)
}

/// Split `"group:artifact"` into owned `(group, artifact)` strings.
fn split_coord(coord: &str) -> Result<(String, String)> {
    let mut parts = coord.splitn(2, ':');
    let group = parts.next().ok_or_else(|| anyhow::anyhow!("invalid coordinate: {coord}"))?;
    let artifact = parts.next().ok_or_else(|| anyhow::anyhow!("invalid coordinate (missing ':'): {coord}"))?;
    Ok((group.to_string(), artifact.to_string()))
}

/// `build-helper-maven-plugin:add-source`/`add-test-source` for source
/// roots beyond the first (which becomes `<sourceDirectory>`/
/// `<testSourceDirectory>`, see [`write_build`]).
fn build_helper_plugins(layout: &MavenLayout) -> Vec<MavenPlugin> {
    let extra_src = layout.src_roots.iter().skip(1);
    let extra_test = layout.test_roots.iter().skip(1);

    let mut executions = Vec::new();
    let src_sources: Vec<XmlNode> = extra_src.map(|r| XmlNode::text("source", path_to_maven(r))).collect();
    if !src_sources.is_empty() {
        executions.push(MavenExecution {
            id: Some("add-source".to_string()),
            phase: Some("generate-sources".to_string()),
            goals: vec!["add-source".to_string()],
            configuration: vec![XmlNode::element("sources", src_sources)],
        });
    }
    let test_sources: Vec<XmlNode> = extra_test.map(|r| XmlNode::text("source", path_to_maven(r))).collect();
    if !test_sources.is_empty() {
        executions.push(MavenExecution {
            id: Some("add-test-source".to_string()),
            phase: Some("generate-test-sources".to_string()),
            goals: vec!["add-test-source".to_string()],
            configuration: vec![XmlNode::element("sources", test_sources)],
        });
    }

    if executions.is_empty() {
        return Vec::new();
    }
    vec![MavenPlugin {
        group_id: Some(BUILD_HELPER_GROUP_ID.to_string()),
        artifact_id: BUILD_HELPER_ARTIFACT_ID.to_string(),
        version: plugin_versions::BUILD_HELPER.to_string(),
        executions,
        ..Default::default()
    }]
}

/// Render a path relative to the project root using `/` separators
/// regardless of host OS, for portable POM output.
fn path_to_maven(p: &Path) -> String {
    p.components().map(|c| c.as_os_str().to_string_lossy()).collect::<Vec<_>>().join("/")
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

type XmlWriter<'a> = Writer<Cursor<&'a mut Vec<u8>>>;

/// Render `project` as a `pom.xml` document, with the `curie-maven-fingerprint`
/// header comment set to `fingerprint_hex`.
pub fn render(project: &MavenProject, fingerprint_hex: &str) -> Result<String> {
    let mut buf = Vec::new();
    let mut w = Writer::new_with_indent(Cursor::new(&mut buf), b' ', 2);

    w.write_event(Event::Decl(BytesDecl::new("1.0", Some("UTF-8"), None)))?;

    let comment = format!(" {GENERATED_MARKER}\n     {FINGERPRINT_PREFIX}{fingerprint_hex} ");
    w.write_event(Event::Comment(BytesText::from_escaped(comment)))?;

    let mut project_el = BytesStart::new("project");
    project_el.push_attribute(("xmlns", "http://maven.apache.org/POM/4.0.0"));
    project_el.push_attribute(("xmlns:xsi", "http://www.w3.org/2001/XMLSchema-instance"));
    project_el.push_attribute((
        "xsi:schemaLocation",
        "http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd",
    ));
    w.write_event(Event::Start(project_el))?;

    text_elem(&mut w, "modelVersion", "4.0.0")?;
    text_elem(&mut w, "groupId", &project.group_id)?;
    text_elem(&mut w, "artifactId", &project.artifact_id)?;
    text_elem(&mut w, "version", &project.version)?;
    text_elem(&mut w, "packaging", &project.packaging)?;
    text_elem(&mut w, "name", &project.artifact_id)?;

    write_properties(&mut w, &project.properties)?;
    write_dependency_management(&mut w, &project.managed_dependencies)?;
    write_dependencies(&mut w, &project.dependencies)?;
    write_build(&mut w, project)?;

    w.write_event(Event::End(BytesEnd::new("project")))?;

    let mut out = String::from_utf8(buf)?;
    out.push('\n');
    Ok(out)
}

fn text_elem(w: &mut XmlWriter<'_>, name: &str, text: &str) -> Result<()> {
    w.create_element(name).write_text_content(BytesText::new(text))?;
    Ok(())
}

fn write_properties(w: &mut XmlWriter<'_>, props: &[(String, String)]) -> Result<()> {
    if props.is_empty() {
        return Ok(());
    }
    w.write_event(Event::Start(BytesStart::new("properties")))?;
    for (key, value) in props {
        text_elem(w, key, value)?;
    }
    w.write_event(Event::End(BytesEnd::new("properties")))?;
    Ok(())
}

fn write_dependency_management(w: &mut XmlWriter<'_>, managed: &[MavenManagedDependency]) -> Result<()> {
    if managed.is_empty() {
        return Ok(());
    }
    w.write_event(Event::Start(BytesStart::new("dependencyManagement")))?;
    w.write_event(Event::Start(BytesStart::new("dependencies")))?;
    for dep in managed {
        w.write_event(Event::Start(BytesStart::new("dependency")))?;
        text_elem(w, "groupId", &dep.group_id)?;
        text_elem(w, "artifactId", &dep.artifact_id)?;
        text_elem(w, "version", &dep.version)?;
        if dep.is_import {
            text_elem(w, "type", "pom")?;
            text_elem(w, "scope", "import")?;
        }
        w.write_event(Event::End(BytesEnd::new("dependency")))?;
    }
    w.write_event(Event::End(BytesEnd::new("dependencies")))?;
    w.write_event(Event::End(BytesEnd::new("dependencyManagement")))?;
    Ok(())
}

fn write_dependencies(w: &mut XmlWriter<'_>, deps: &[MavenDependency]) -> Result<()> {
    if deps.is_empty() {
        return Ok(());
    }
    w.write_event(Event::Start(BytesStart::new("dependencies")))?;
    for dep in deps {
        w.write_event(Event::Start(BytesStart::new("dependency")))?;
        text_elem(w, "groupId", &dep.group_id)?;
        text_elem(w, "artifactId", &dep.artifact_id)?;
        if let Some(version) = &dep.version {
            text_elem(w, "version", version)?;
        }
        if let Some(scope) = &dep.scope {
            text_elem(w, "scope", scope)?;
        }
        if !dep.exclusions.is_empty() {
            w.write_event(Event::Start(BytesStart::new("exclusions")))?;
            for (group_id, artifact_id) in &dep.exclusions {
                w.write_event(Event::Start(BytesStart::new("exclusion")))?;
                text_elem(w, "groupId", group_id)?;
                text_elem(w, "artifactId", artifact_id)?;
                w.write_event(Event::End(BytesEnd::new("exclusion")))?;
            }
            w.write_event(Event::End(BytesEnd::new("exclusions")))?;
        }
        w.write_event(Event::End(BytesEnd::new("dependency")))?;
    }
    w.write_event(Event::End(BytesEnd::new("dependencies")))?;
    Ok(())
}

fn write_build(w: &mut XmlWriter<'_>, project: &MavenProject) -> Result<()> {
    let layout = &project.layout;

    // Maven defaults `<sourceDirectory>`/`<testSourceDirectory>` to
    // src/main/java and src/test/java; only emit them when the first root
    // differs (e.g. flat-package layouts).
    let source_directory = layout
        .src_roots
        .first()
        .filter(|r| r.as_path() != Path::new("src/main/java"));
    let test_source_directory = layout
        .test_roots
        .first()
        .filter(|r| r.as_path() != Path::new("src/test/java"));

    let has_build_content = source_directory.is_some()
        || test_source_directory.is_some()
        || layout.resources.is_some()
        || layout.test_resources.is_some()
        || !project.plugins.is_empty();

    if !has_build_content {
        return Ok(());
    }

    w.write_event(Event::Start(BytesStart::new("build")))?;
    if let Some(dir) = source_directory {
        text_elem(w, "sourceDirectory", &path_to_maven(dir))?;
    }
    if let Some(dir) = test_source_directory {
        text_elem(w, "testSourceDirectory", &path_to_maven(dir))?;
    }
    write_resource_block(w, "resources", "resource", layout.resources.as_deref())?;
    write_resource_block(w, "testResources", "testResource", layout.test_resources.as_deref())?;
    write_plugins(w, &project.plugins)?;
    w.write_event(Event::End(BytesEnd::new("build")))?;
    Ok(())
}

/// Writes `<resources><resource><directory>dir</directory></resource></resources>`
/// (or the `testResources`/`testResource` equivalent), explicit even for
/// Maven's default locations so the POM is self-describing. No-op if `dir`
/// is `None`.
fn write_resource_block(w: &mut XmlWriter<'_>, outer: &str, inner: &str, dir: Option<&Path>) -> Result<()> {
    let Some(dir) = dir else { return Ok(()) };
    w.write_event(Event::Start(BytesStart::new(outer)))?;
    w.write_event(Event::Start(BytesStart::new(inner)))?;
    text_elem(w, "directory", &path_to_maven(dir))?;
    w.write_event(Event::End(BytesEnd::new(inner)))?;
    w.write_event(Event::End(BytesEnd::new(outer)))?;
    Ok(())
}

fn write_plugins(w: &mut XmlWriter<'_>, plugins: &[MavenPlugin]) -> Result<()> {
    if plugins.is_empty() {
        return Ok(());
    }
    w.write_event(Event::Start(BytesStart::new("plugins")))?;
    for plugin in plugins {
        write_plugin(w, plugin)?;
    }
    w.write_event(Event::End(BytesEnd::new("plugins")))?;
    Ok(())
}

fn write_plugin(w: &mut XmlWriter<'_>, plugin: &MavenPlugin) -> Result<()> {
    w.write_event(Event::Start(BytesStart::new("plugin")))?;
    text_elem(w, "groupId", plugin.group_id.as_deref().unwrap_or(DEFAULT_PLUGIN_GROUP_ID))?;
    text_elem(w, "artifactId", &plugin.artifact_id)?;
    text_elem(w, "version", &plugin.version)?;
    write_xml_nodes_in(w, "configuration", &plugin.configuration)?;
    write_executions(w, &plugin.executions)?;
    w.write_event(Event::End(BytesEnd::new("plugin")))?;
    Ok(())
}

fn write_executions(w: &mut XmlWriter<'_>, executions: &[MavenExecution]) -> Result<()> {
    if executions.is_empty() {
        return Ok(());
    }
    w.write_event(Event::Start(BytesStart::new("executions")))?;
    for exec in executions {
        w.write_event(Event::Start(BytesStart::new("execution")))?;
        if let Some(id) = &exec.id {
            text_elem(w, "id", id)?;
        }
        if let Some(phase) = &exec.phase {
            text_elem(w, "phase", phase)?;
        }
        if !exec.goals.is_empty() {
            w.write_event(Event::Start(BytesStart::new("goals")))?;
            for goal in &exec.goals {
                text_elem(w, "goal", goal)?;
            }
            w.write_event(Event::End(BytesEnd::new("goals")))?;
        }
        write_xml_nodes_in(w, "configuration", &exec.configuration)?;
        w.write_event(Event::End(BytesEnd::new("execution")))?;
    }
    w.write_event(Event::End(BytesEnd::new("executions")))?;
    Ok(())
}

/// Writes `<wrapper>...nodes...</wrapper>`, or nothing when `nodes` is empty.
fn write_xml_nodes_in(w: &mut XmlWriter<'_>, wrapper: &str, nodes: &[XmlNode]) -> Result<()> {
    if nodes.is_empty() {
        return Ok(());
    }
    w.write_event(Event::Start(BytesStart::new(wrapper)))?;
    for node in nodes {
        write_xml_node(w, node)?;
    }
    w.write_event(Event::End(BytesEnd::new(wrapper)))?;
    Ok(())
}

fn write_xml_node(w: &mut XmlWriter<'_>, node: &XmlNode) -> Result<()> {
    match node {
        XmlNode::Text(name, value) => text_elem(w, name, value),
        XmlNode::Element(name, children) => {
            w.write_event(Event::Start(BytesStart::new(name.as_str())))?;
            for child in children {
                write_xml_node(w, child)?;
            }
            w.write_event(Event::End(BytesEnd::new(name.as_str())))?;
            Ok(())
        }
    }
}

// ---------------------------------------------------------------------------
// Fingerprint + incremental write
// ---------------------------------------------------------------------------

/// SHA-256 fingerprint of everything that can change a generated POM:
/// generator schema version, the member's `Curie.toml` bytes, the
/// effective workspace `Curie.toml` bytes (when in a workspace), the
/// sorted source/test/resource root list, and the sorted `pinTransitive`
/// closure (empty when disabled).
pub fn fingerprint(
    schema_version: u32,
    member_toml: &[u8],
    workspace_toml: Option<&[u8]>,
    layout: &MavenLayout,
    pinned: &[PinnedDependency],
) -> String {
    let mut hasher = Sha256::new();
    hasher.update(schema_version.to_le_bytes());
    hasher.update(member_toml);
    if let Some(ws) = workspace_toml {
        hasher.update(ws);
    }

    let mut roots: Vec<String> = Vec::new();
    for r in &layout.src_roots {
        roots.push(format!("src:{}", path_to_maven(r)));
    }
    for r in &layout.test_roots {
        roots.push(format!("test:{}", path_to_maven(r)));
    }
    if let Some(r) = &layout.resources {
        roots.push(format!("resources:{}", path_to_maven(r)));
    }
    if let Some(r) = &layout.test_resources {
        roots.push(format!("test-resources:{}", path_to_maven(r)));
    }
    for pattern in &layout.colocated_test_excludes {
        roots.push(format!("exclude:{pattern}"));
    }
    roots.sort();
    for r in &roots {
        hasher.update(r.as_bytes());
        hasher.update(b"\0");
    }

    let mut pins = pinned.to_vec();
    pins.sort();
    for pin in &pins {
        hasher.update(format!("{}:{}:{}", pin.group_id, pin.artifact_id, pin.version).as_bytes());
        hasher.update(b"\0");
    }

    hex::encode(hasher.finalize())
}

/// Outcome of [`sync_pom`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SyncOutcome {
    /// The existing file already matches; nothing was written.
    UpToDate,
    /// The file was created or rewritten.
    Written,
}

/// Generate (or refresh) `pom_path` for `desc`, writing only when the
/// content actually changes.
///
/// `member_toml`/`workspace_toml`/`pinned` feed [`fingerprint`]. When
/// `pom_path` already exists without a `curie-maven-fingerprint` marker
/// (a hand-written POM), this errors unless `force` is `true`.
pub fn sync_pom(
    project_root: &Path,
    pom_path: &Path,
    desc: &Descriptor,
    member_toml: &[u8],
    workspace_toml: Option<&[u8]>,
    pinned: &[PinnedDependency],
    force: bool,
) -> Result<SyncOutcome> {
    let project = build_project(desc, project_root, pinned)?;
    let fp = fingerprint(SCHEMA_VERSION, member_toml, workspace_toml, &project.layout, pinned);

    if let Ok(existing) = std::fs::read_to_string(pom_path) {
        match extract_fingerprint(&existing) {
            Some(existing_fp) if existing_fp == fp => return Ok(SyncOutcome::UpToDate),
            None if !force => return Err(unmarked_pom_error(pom_path)),
            _ => {}
        }
    }

    let rendered = render(&project, &fp)?;
    let unchanged = std::fs::read(pom_path).map(|existing| existing == rendered.as_bytes()).unwrap_or(false);
    if unchanged {
        return Ok(SyncOutcome::UpToDate);
    }

    if let Some(parent) = pom_path.parent() {
        std::fs::create_dir_all(parent).with_context(|| format!("failed to create {}", parent.display()))?;
    }
    std::fs::write(pom_path, rendered.as_bytes())
        .with_context(|| format!("failed to write {}", pom_path.display()))?;
    Ok(SyncOutcome::Written)
}

/// Extract the `curie-maven-fingerprint: <hex>` value from a generated
/// POM's header comment, if present.
fn extract_fingerprint(xml: &str) -> Option<String> {
    xml.lines().find_map(|line| line.trim().strip_prefix(FINGERPRINT_PREFIX)).map(|s| s.trim().to_string())
}

fn unmarked_pom_error(pom_path: &Path) -> anyhow::Error {
    anyhow::anyhow!(
        "{path} already exists and was not generated by `curie maven sync` \
         (no curie-maven-fingerprint marker found). To proceed, either:\n\
         \x20 - delete {path} and re-run `curie maven sync`,\n\
         \x20 - run `curie maven sync --force` to overwrite it, or\n\
         \x20 - remove `[maven] sync = true` from Curie.toml to disable sync.",
        path = pom_path.display(),
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::descriptor::{Application, DescriptorKind, MavenConfig, *};
    use std::collections::BTreeMap;

    fn minimal_app(name: &str, group_id: Option<&str>) -> Descriptor {
        Descriptor {
            kind: DescriptorKind::Application(Application {
                name: name.to_string(),
                version: "1.0.0".to_string(),
                group_id: group_id.map(String::from),
                main_class: Some("Main".to_string()),
            }),
            java: Java::default(),
            test: Test::default(),
            kotlin: Kotlin::default(),
            groovy: Groovy::default(),
            spock: Spock::default(),
            native_image: NativeImage::default(),
            docker: Docker::default(),
            build_info: BuildInfo::default(),
            fat_jar: FatJar::default(),
            dependencies: BTreeMap::new(),
            test_dependencies: BTreeMap::new(),
            repositories: vec![],
            bom_imports: BTreeMap::new(),
            test_bom_imports: BTreeMap::new(),
            inherited_bom_imports: BTreeMap::new(),
            inherited_test_bom_imports: BTreeMap::new(),
            workspace_dependencies: BTreeMap::new(),
            annotation_processors: BTreeMap::new(),
            test_annotation_processors: BTreeMap::new(),
            inherited_annotation_processors: BTreeMap::new(),
            inherited_test_annotation_processors: BTreeMap::new(),
            annotation_processor_options: BTreeMap::new(),
            test_annotation_processor_options: BTreeMap::new(),
            inherited_annotation_processor_options: BTreeMap::new(),
            inherited_test_annotation_processor_options: BTreeMap::new(),
            publish: PublishConfig::default(),
            plugins: BTreeMap::new(),
            maven: MavenConfig::default(),
        }
    }

    fn write_file(dir: &Path, rel: &str, contents: &str) {
        let path = dir.join(rel);
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(path, contents).unwrap();
    }

    // -- coordinates ----------------------------------------------------------

    #[test]
    fn coordinates_and_groupid_fallback() {
        let dir = tempfile::tempdir().unwrap();
        let with_group = minimal_app("my-app", Some("com.example"));
        let project = build_project(&with_group, dir.path(), &[]).unwrap();
        assert_eq!(project.group_id, "com.example");
        assert_eq!(project.artifact_id, "my-app");
        assert_eq!(project.version, "1.0.0");
        assert_eq!(project.packaging, "jar");

        let without_group = minimal_app("my-app", None);
        let project = build_project(&without_group, dir.path(), &[]).unwrap();
        assert_eq!(project.group_id, GENERATED_GROUP_ID);
    }

    #[test]
    fn properties_include_release_encoding_and_output_timestamp() {
        let dir = tempfile::tempdir().unwrap();
        let mut desc = minimal_app("my-app", Some("com.example"));
        desc.java.source_compatibility = Some("17".to_string());
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        let xml = render(&project, "deadbeef").unwrap();
        assert!(xml.contains("<maven.compiler.release>17</maven.compiler.release>"));
        assert!(xml.contains("<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>"));
        assert!(xml.contains(&format!("<project.build.outputTimestamp>{OUTPUT_TIMESTAMP}</project.build.outputTimestamp>")));
    }

    // -- dependencies -----------------------------------------------------------

    #[test]
    fn dependencies_get_compile_and_test_scopes_with_exclusions() {
        let dir = tempfile::tempdir().unwrap();
        let mut desc = minimal_app("my-app", Some("com.example"));
        desc.dependencies.insert(
            "com.fasterxml.jackson.core:jackson-databind".to_string(),
            DependencyValue::Detailed(DependencyDetailed {
                version: "2.17.2".to_string(),
                repository: None,
                java_agent: false,
                exclusions: vec!["com.fasterxml.jackson.core:jackson-annotations".to_string()],
                shade: None,
                relocations: vec![],
            }),
        );
        desc.test_dependencies.insert(
            "org.junit.jupiter:junit-jupiter".to_string(),
            DependencyValue::Version("5.10.0".to_string()),
        );
        let project = build_project(&desc, dir.path(), &[]).unwrap();

        let prod = project.dependencies.iter().find(|d| d.artifact_id == "jackson-databind").unwrap();
        assert_eq!(prod.scope.as_deref(), Some("compile"));
        assert_eq!(prod.exclusions, vec![("com.fasterxml.jackson.core".to_string(), "jackson-annotations".to_string())]);

        let test = project.dependencies.iter().find(|d| d.artifact_id == "junit-jupiter").unwrap();
        assert_eq!(test.scope.as_deref(), Some("test"));

        let xml = render(&project, "deadbeef").unwrap();
        assert!(xml.contains("<scope>compile</scope>"));
        assert!(xml.contains("<scope>test</scope>"));
        assert!(xml.contains("<exclusions>"));
        assert!(xml.contains("<artifactId>jackson-annotations</artifactId>"));
    }

    #[test]
    fn version_blank_dep_emitted_without_version_tag() {
        let dir = tempfile::tempdir().unwrap();
        let mut desc = minimal_app("my-app", Some("com.example"));
        desc.dependencies.insert(
            "com.fasterxml.jackson.core:jackson-databind".to_string(),
            DependencyValue::Version(String::new()),
        );
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        let dep = project.dependencies.iter().find(|d| d.artifact_id == "jackson-databind").unwrap();
        assert_eq!(dep.version, None);

        let xml = render(&project, "deadbeef").unwrap();
        let dep_block = xml.split("<dependency>").find(|b| b.contains("jackson-databind")).unwrap();
        assert!(!dep_block.contains("<version>"), "blank version must not render <version>: {dep_block}");
    }

    // -- BOM imports / pinTransitive ---------------------------------------------

    #[test]
    fn bom_imports_member_before_workspace() {
        let dir = tempfile::tempdir().unwrap();
        let mut desc = minimal_app("my-app", Some("com.example"));
        desc.bom_imports.insert("com.example:member-bom".to_string(), "1.0".to_string());
        desc.inherited_bom_imports.insert("com.example:workspace-bom".to_string(), "2.0".to_string());
        let project = build_project(&desc, dir.path(), &[]).unwrap();

        assert_eq!(project.managed_dependencies.len(), 2);
        assert_eq!(project.managed_dependencies[0].artifact_id, "member-bom");
        assert_eq!(project.managed_dependencies[1].artifact_id, "workspace-bom");
        assert!(project.managed_dependencies.iter().all(|d| d.is_import));

        let xml = render(&project, "deadbeef").unwrap();
        let member_pos = xml.find("member-bom").unwrap();
        let workspace_pos = xml.find("workspace-bom").unwrap();
        assert!(member_pos < workspace_pos);
    }

    #[test]
    fn pin_transitive_off_by_default_no_pinned_entries() {
        let dir = tempfile::tempdir().unwrap();
        let desc = minimal_app("my-app", Some("com.example"));
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        assert!(project.managed_dependencies.is_empty());
        assert!(!desc.maven.pin_transitive_enabled());
    }

    #[test]
    fn pin_transitive_emits_sorted_dependency_management_before_bom_imports() {
        let dir = tempfile::tempdir().unwrap();
        let mut desc = minimal_app("my-app", Some("com.example"));
        desc.bom_imports.insert("com.example:member-bom".to_string(), "1.0".to_string());
        let pinned = vec![
            PinnedDependency { group_id: "org.slf4j".into(), artifact_id: "slf4j-api".into(), version: "2.0.12".into() },
            PinnedDependency { group_id: "com.google.guava".into(), artifact_id: "guava".into(), version: "33.2.0-jre".into() },
        ];
        let project = build_project(&desc, dir.path(), &pinned).unwrap();

        // Sorted by group:artifact, listed before BOM imports, not marked as imports.
        assert_eq!(project.managed_dependencies[0].group_id, "com.google.guava");
        assert_eq!(project.managed_dependencies[1].group_id, "org.slf4j");
        assert!(!project.managed_dependencies[0].is_import);
        assert!(!project.managed_dependencies[1].is_import);
        assert_eq!(project.managed_dependencies[2].artifact_id, "member-bom");

        let xml = render(&project, "deadbeef").unwrap();
        let guava_pos = xml.find("guava").unwrap();
        let bom_pos = xml.find("member-bom").unwrap();
        assert!(guava_pos < bom_pos);
    }

    // -- layout -----------------------------------------------------------------

    #[test]
    fn maven_layout_keeps_defaults() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        write_file(dir.path(), "src/test/java/com/example/HelloTest.java", "package com.example; class HelloTest {}");

        let layout = discover_layout(dir.path());
        assert_eq!(layout.src_roots, vec![PathBuf::from("src/main/java")]);
        assert_eq!(layout.test_roots, vec![PathBuf::from("src/test/java")]);
        assert!(layout.colocated_test_excludes.is_empty());

        let desc = minimal_app("my-app", Some("com.example"));
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        let xml = render(&project, "deadbeef").unwrap();
        assert!(!xml.contains("<sourceDirectory>"));
        assert!(!xml.contains("<testSourceDirectory>"));
    }

    #[test]
    fn flat_layout_sets_sourcedir_and_testdir() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/com.example.app/Hello.java", "package com.example.app; class Hello {}");
        write_file(dir.path(), "tests/com.example.app/HelloTest.java", "package com.example.app; class HelloTest {}");

        let layout = discover_layout(dir.path());
        assert_eq!(layout.src_roots, vec![PathBuf::from("src/com.example.app")]);
        assert_eq!(layout.test_roots, vec![PathBuf::from("tests/com.example.app")]);

        let desc = minimal_app("my-app", Some("com.example"));
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        let xml = render(&project, "deadbeef").unwrap();
        assert!(xml.contains("<sourceDirectory>src/com.example.app</sourceDirectory>"));
        assert!(xml.contains("<testSourceDirectory>tests/com.example.app</testSourceDirectory>"));
    }

    #[test]
    fn extra_source_root_becomes_build_helper_add_source() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        write_file(dir.path(), "src/main/kotlin/com/example/World.kt", "package com.example\nclass World");

        let layout = discover_layout(dir.path());
        assert_eq!(layout.src_roots, vec![PathBuf::from("src/main/java"), PathBuf::from("src/main/kotlin")]);

        let desc = minimal_app("my-app", Some("com.example"));
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        let xml = render(&project, "deadbeef").unwrap();
        // src/main/java is the Maven default and stays implicit.
        assert!(!xml.contains("<sourceDirectory>"));
        assert!(xml.contains("build-helper-maven-plugin"));
        assert!(xml.contains("<source>src/main/kotlin</source>"));
        assert!(xml.contains("<goal>add-source</goal>"));
    }

    #[test]
    fn colocated_test_patterns_excluded_from_main_compile() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        write_file(dir.path(), "src/main/java/com/example/HelloTest.java", "package com.example; class HelloTest {}");

        let layout = discover_layout(dir.path());
        assert_eq!(layout.colocated_test_excludes, vec!["**/*Test.java".to_string(), "**/*Tests.java".to_string(), "**/*Spec.java".to_string()]);
        // The production root is also a test source root for the co-located tests.
        assert!(layout.test_roots.contains(&PathBuf::from("src/main/java")));
    }

    #[test]
    fn resources_are_explicit_even_at_default_location() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        write_file(dir.path(), "src/main/resources/app.properties", "a=b");

        let desc = minimal_app("my-app", Some("com.example"));
        let project = build_project(&desc, dir.path(), &[]).unwrap();
        let xml = render(&project, "deadbeef").unwrap();
        assert!(xml.contains("<resources>"));
        assert!(xml.contains("<directory>src/main/resources</directory>"));
    }

    // -- determinism / incrementality --------------------------------------------

    #[test]
    fn same_inputs_render_byte_identical_pom() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        let desc = minimal_app("my-app", Some("com.example"));

        let p1 = build_project(&desc, dir.path(), &[]).unwrap();
        let p2 = build_project(&desc, dir.path(), &[]).unwrap();
        assert_eq!(render(&p1, "deadbeef").unwrap(), render(&p2, "deadbeef").unwrap());
    }

    #[test]
    fn fingerprint_changes_with_schema_version() {
        let layout = MavenLayout::default();
        let fp1 = fingerprint(1, b"toml", None, &layout, &[]);
        let fp2 = fingerprint(2, b"toml", None, &layout, &[]);
        assert_ne!(fp1, fp2);
    }

    #[test]
    fn pom_not_rewritten_when_fingerprint_unchanged() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        let desc = minimal_app("my-app", Some("com.example"));
        let pom_path = dir.path().join("pom.xml");

        let outcome = sync_pom(dir.path(), &pom_path, &desc, b"toml-bytes", None, &[], false).unwrap();
        assert_eq!(outcome, SyncOutcome::Written);

        let metadata_before = std::fs::metadata(&pom_path).unwrap();
        let modified_before = metadata_before.modified().unwrap();

        let outcome = sync_pom(dir.path(), &pom_path, &desc, b"toml-bytes", None, &[], false).unwrap();
        assert_eq!(outcome, SyncOutcome::UpToDate);

        let modified_after = std::fs::metadata(&pom_path).unwrap().modified().unwrap();
        assert_eq!(modified_before, modified_after);
    }

    #[test]
    fn pom_rewritten_when_curie_toml_changes() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        let desc = minimal_app("my-app", Some("com.example"));
        let pom_path = dir.path().join("pom.xml");

        sync_pom(dir.path(), &pom_path, &desc, b"v1", None, &[], false).unwrap();
        let outcome = sync_pom(dir.path(), &pom_path, &desc, b"v2", None, &[], false).unwrap();
        assert_eq!(outcome, SyncOutcome::Written);
    }

    #[test]
    fn pom_rewritten_when_source_root_added() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        let desc = minimal_app("my-app", Some("com.example"));
        let pom_path = dir.path().join("pom.xml");

        sync_pom(dir.path(), &pom_path, &desc, b"toml", None, &[], false).unwrap();
        let outcome = sync_pom(dir.path(), &pom_path, &desc, b"toml", None, &[], false).unwrap();
        assert_eq!(outcome, SyncOutcome::UpToDate);

        write_file(dir.path(), "src/main/kotlin/com/example/World.kt", "package com.example\nclass World");
        let outcome = sync_pom(dir.path(), &pom_path, &desc, b"toml", None, &[], false).unwrap();
        assert_eq!(outcome, SyncOutcome::Written);
    }

    #[test]
    fn refuses_to_overwrite_unmarked_pom() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        let desc = minimal_app("my-app", Some("com.example"));
        let pom_path = dir.path().join("pom.xml");
        std::fs::write(&pom_path, "<project>hand written</project>").unwrap();

        let err = sync_pom(dir.path(), &pom_path, &desc, b"toml", None, &[], false).unwrap_err().to_string();
        assert!(err.contains("--force"), "got: {err}");
        assert_eq!(std::fs::read_to_string(&pom_path).unwrap(), "<project>hand written</project>");
    }

    #[test]
    fn force_overwrites_unmarked_pom() {
        let dir = tempfile::tempdir().unwrap();
        write_file(dir.path(), "src/main/java/com/example/Hello.java", "package com.example; class Hello {}");
        let desc = minimal_app("my-app", Some("com.example"));
        let pom_path = dir.path().join("pom.xml");
        std::fs::write(&pom_path, "<project>hand written</project>").unwrap();

        let outcome = sync_pom(dir.path(), &pom_path, &desc, b"toml", None, &[], true).unwrap();
        assert_eq!(outcome, SyncOutcome::Written);
        assert!(std::fs::read_to_string(&pom_path).unwrap().contains("curie-maven-fingerprint"));
    }
}
